services:
  db:
    image: postgres:14-alpine
    restart: always
    healthcheck:
      # test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
    ports:
      - "5433:5433"
    expose:
      - "5433"
    command: -p 5433
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
  api:
    build: .
    container_name: "api"
    volumes:
      - ./app:/app
    ports:
      - 8000:8000
    depends_on:
      - db

volumes:
  app-db-data: