services:
  db:
    image: postgres:14-alpine
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PG_USER} -d ${PG_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
    ports:
      - "5433:5432"
    expose:
      - "5432"
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_DB=${PG_DB}
  api:
    build: .
    container_name: "api"
    volumes:
      - ./app:/app
    ports:
      - ${BACKEND_PORT}:8000
    environment:
      - PG_HOST=db
      - PG_PORT=5432
      - PG_USER=${PG_USER}
      - PG_PASSWORD=${PG_PASSWORD}
      - PG_DB=${PG_DB}
      - SQLALCHEMY_ECHO=true
    tty: true
    depends_on:
      - db
    env_file:
      - .env

volumes:
  app-db-data: