services:
  db:
    image: postgres:14-alpine
    restart: always
    healthcheck:
      # test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
    ports:
      - "${PG_PORT}:${PG_PORT}"
    expose:
      - "${PG_PORT}"
    command: -p ${PG_PORT}
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_DB=${PG_DB}
  api:
    build: .
    container_name: "api"
    volumes:
      - ./app:/app
    ports:
      - ${BACKEND_PORT}:8000
    depends_on:
      - db
    env_file:
      - .env

volumes:
  app-db-data: