[tool.ruff]
line-length = 88
select = ["E", "F", "I", "B"]
fixable = ["ALL"]

[tool.ruff.per-file-ignores]
"app/alembic/env.py" = ["E402"]  # Allow imports after sys.path modification

[tool.black]
line-length = 88
target-version = ["py311"]
