"""002 Allow 211 to have no closed data value.

Revision ID: 002
Revises: 001
Create Date: 2025-07-03 19:54:46.395499

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "002"
down_revision: Union[str, None] = "001"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("form211", "closed_at", existing_type=sa.DATETIME(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("form211", "closed_at", existing_type=sa.DATETIME(), nullable=False)
    # ### end Alembic commands ###
