"""Add new 211 fields.

Revision ID: 004
Revises: 0557b5eacddf
Create Date: 2025-06-12 20:05:13.464776

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "004"
down_revision: Union[str, None] = "0557b5eacddf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("form211", sa.Column("created_by", sa.Integer(), nullable=False))
    op.add_column(
        "form211", sa.Column("operational_period", sa.Integer(), nullable=False)
    )
    op.add_column(
        "form211",
        sa.Column(
            "closed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.create_foreign_key(
        op.f("fk_form211_created_by_users"), "form211", "users", ["created_by"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_form211_created_by_users"), "form211", type_="foreignkey"
    )
    op.drop_column("form211", "closed_at")
    op.drop_column("form211", "operational_period")
    op.drop_column("form211", "created_by")
    # ### end Alembic commands ###
