name: Build and Push Docker Image

on:
  pull_request:
    types:
      - closed
    branches:
      - main
    paths:
      - '**'  # Any changes in the backend repository

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Check if PR was merged
      if: github.event.pull_request.merged == true
      run: echo "PR was merged"

    - name: Extract PR number
      if: github.event.pull_request.merged == true
      shell: bash
      run: echo "PR_NUMBER=$(echo ${{ github.event.pull_request.number }})" >> $GITHUB_ENV

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: |
          wagoneerguy/fsar211-backend:latest
          wagoneerguy/fsar211-backend:pr-${{ env.PR_NUMBER }}-${{ github.sha }}
        cache-from: type=registry,ref=wagoneerguy/fsar211-backend:latest
        cache-to: type=inline

    - name: Deploy to production
      if: github.event.pull_request.merged == true
      env:
        SSH_PRIVATE_KEY: ${{ secrets.PROD_SSH_KEY }}
        DEPLOY_HOST: ${{ secrets.PROD_HOST }}
        DEPLOY_USER: ${{ secrets.PROD_SSH_USER }}
      run: |
        # Setup SSH key
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/deploy_key
        chmod 600 ~/.ssh/deploy_key
        echo "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config

        # Deploy commands
        ssh -i ~/.ssh/deploy_key $DEPLOY_USER@$DEPLOY_HOST << 'ENDSSH'
          # Pull new image
          docker pull wagoneerguy/fsar211-backend:latest

          # Stop and remove existing container
          docker stop fsar211-backend 2>/dev/null || true
          docker rm fsar211-backend 2>/dev/null || true

          # Run new container
          docker run -d --name fsar211-backend \
            --network fsar211-network \
            -p 8000:8000 \
            --env-file /tmp/backend.env \
            wagoneerguy/fsar211-backend:latest

          # Run migrations
          docker exec fsar211-backend alembic upgrade head
        ENDSSH
