name: Build and Push Docker Image

on:
  pull_request:
    types:
      - closed
    branches:
      - main
    paths:
      - '**'  # Any changes in the backend repository

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Check if PR was merged
      if: github.event.pull_request.merged == true
      run: echo "PR was merged"

    - name: Extract PR number
      if: github.event.pull_request.merged == true
      shell: bash
      run: echo "PR_NUMBER=$(echo ${{ github.event.pull_request.number }})" >> $GITHUB_ENV

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: ./fsar211-backend
        push: true
        tags: |
          wagoneerguy/fsar211-backend:latest
          wagoneerguy/fsar211-backend:pr-${{ env.PR_NUMBER }}-${{ github.sha }}
        cache-from: type=registry,ref=wagoneerguy/fsar211-backend:latest
        cache-to: type=inline
