name: Build and Push Docker Image

on:
  pull_request:
    types:
      - opened      # Triggered when PR is created
      - synchronize # Triggered when PR branch is updated
      - closed      # Triggered when PR is merged or closed
    branches:
      - main
    paths:
      - '**'  # Any changes in the backend repository

permissions:
  deployments: write
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Check if PR was merged
      if: github.event.pull_request.merged == true
      run: echo "PR was merged"

    - name: Extract PR number
      if: github.event.pull_request.merged == true
      shell: bash
      run: echo "PR_NUMBER=$(echo ${{ github.event.pull_request.number }})" >> $GITHUB_ENV

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: |
          wagoneerguy/fsar211-backend:latest
          wagoneerguy/fsar211-backend:pr-${{ env.PR_NUMBER }}-${{ github.sha }}
        cache-from: type=registry,ref=wagoneerguy/fsar211-backend:latest
        cache-to: type=inline

    - name: Create deployment status
      # Temporarily deploying on any PR event for testing
      uses: bobheadxi/deployments@v1
      id: deployment
      with:
        step: start
        token: ${{ secrets.GITHUB_TOKEN }}
        env: production

    - name: Setup SSH and test connection
      # Temporarily deploying on any PR event for testing
      env:
        SSH_PRIVATE_KEY: ${{ secrets.PROD_SSH_KEY }}
        DEPLOY_HOST: ${{ secrets.PROD_HOST }}
        DEPLOY_USER: ${{ secrets.PROD_SSH_USER }}
      run: |
        # Setup SSH key
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/deploy_key
        chmod 600 ~/.ssh/deploy_key
        echo "$DEPLOY_HOST ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIL/wfulejt1Rju8XK61dNS0D/OF/EYBPAibHA25O6/cp" > ~/.ssh/known_hosts

        # Test SSH connection
        if ! ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=accept-new $DEPLOY_USER@$DEPLOY_HOST 'echo "SSH Connection Successful"'; then
          echo "::error::Failed to establish SSH connection"
          exit 1
        fi

    - name: Deploy to production
      # Temporarily deploying on any PR event for testing
      env:
        SSH_PRIVATE_KEY: ${{ secrets.PROD_SSH_KEY }}
        DEPLOY_HOST: ${{ secrets.PROD_HOST }}
        DEPLOY_USER: ${{ secrets.PROD_SSH_USER }}
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      run: |
        # Function to send Slack notification
        notify_slack() {
          if [ -n "$SLACK_WEBHOOK" ]; then
            curl -X POST -H 'Content-type: application/json' \
              --data "{\"text\":\"$1\"}" \
              $SLACK_WEBHOOK
          fi
        }

        # Function to handle errors
        handle_error() {
          error_message="$1"
          echo "::error::$error_message"
          notify_slack ":x: Deployment failed: $error_message"
          exit 1
        }

        notify_slack ":rocket: Starting deployment of fsar211-backend..."

        # Deploy with error handling
        ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=accept-new $DEPLOY_USER@$DEPLOY_HOST << 'ENDSSH' || handle_error "Deployment failed"
          set -e  # Exit on any error

          echo "Pulling new image..."
          docker pull wagoneerguy/fsar211-backend:latest || exit 1

          echo "Stopping old container..."
          docker stop fsar211-backend 2>/dev/null || true
          docker rm fsar211-backend 2>/dev/null || true

          echo "Starting new container..."
          docker run -d --name fsar211-backend \
            --network fsar211-network \
            -p 8000:8000 \
            --env-file /tmp/backend.env \
            wagoneerguy/fsar211-backend:latest || exit 1

          echo "Running migrations..."
          if ! docker exec fsar211-backend alembic upgrade head; then
            echo "Migration failed, rolling back..."
            docker stop fsar211-backend
            docker rm fsar211-backend
            exit 1
          fi

          # Verify service is running
          echo "Verifying service..."
          sleep 5
          if ! curl -s http://localhost:8000 > /dev/null; then
            echo "Service verification failed"
            exit 1
          fi
        ENDSSH

        notify_slack ":white_check_mark: Successfully deployed fsar211-backend!"

    - name: Update deployment status
      if: always() # Temporarily updating status on any PR event
      uses: bobheadxi/deployments@v1
      with:
        step: finish
        token: ${{ secrets.GITHUB_TOKEN }}
        status: ${{ job.status }}
        deployment_id: ${{ steps.deployment.outputs.deployment_id }}
        env_url: https://211.fremontsar.com
